### ISSUE TITLE
Error when trying to play a song

### ISSUE THREAD

**Issue by bimaindrawans** [Beban-Studio/Aria-Melody#1]
[2024-11-28 13:18:59]: /play used by sembarangan on Bacot (1135038471585677353)
[AntiCrash] | [UncaughtExceptionMonitor_Logs] | [START] :
Uncaught exception monitor: Error: Received one or more errors
Exception origin: uncaughtException
[AntiCrash] | [UncaughtExceptionMonitor_Logs] | [END] :
[AntiCrash] | [UncaughtException_Logs] | [START] :
Uncaught exception: Error: Received one or more errors
Exception origin: uncaughtException
[AntiCrash] | [UncaughtException_Logs] | [END] :

![image](https://github.com/user-attachments/assets/9566f10b-5a78-4e5b-a906-0ab6b820bc0d)

**Comment by BebanCode** [comment]
> [2024-11-28 13:18:59]: /play used by sembarangan on Bacot (1135038471585677353) [AntiCrash] | [UncaughtExceptionMonitor_Logs] | [START] : Uncaught exception monitor: Error: Received one or more errors Exception origin: uncaughtException [AntiCrash] | [UncaughtExceptionMonitor_Logs] | [END] : [AntiCrash] | [UncaughtException_Logs] | [START] : Uncaught exception: Error: Received one or more errors Exception origin: uncaughtException [AntiCrash] | [UncaughtException_Logs] | [END] :
> 
> ![image](https://private-user-images.githubusercontent.com/147312348/390649816-9566f10b-5a78-4e5b-a906-0ab6b820bc0d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI3NzM4NTgsIm5iZiI6MTczMjc3MzU1OCwicGF0aCI6Ii8xNDczMTIzNDgvMzkwNjQ5ODE2LTk1NjZmMTBiLTVhNzgtNGU1Yi1hOTA2LTBhYjZiODIwYmMwZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyOFQwNTU5MThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMmQ5YmVjMmMzNjk1OTM5M2RjZTNjYzg2ZjM1ODQzODhjZTAzYzQ1ZjEzYzk1MTIwNDQyMWVkNTI1ZWFhMWNmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.8IO8bqnqOWn9Qfm9i9qGsmaf0mCTkMZX4Rhq-efmfh0)

**Have you fill your config.js/env?**
**It looks like you didn't fill the `default_color` section on config / .env**

Please fill your config.js/env with your bot token and other required information.
You can find your bot token information in the [`Discord Developer Portal`](https://discord.com/developers/applications)
**Usual Required Information:**
- Your bot token
- Your bot ID
- Your bot default embed color
- MongoDB URL ( for some bot its required )
- Developer IDs
- etc...

You can check the readme file or check the cofiguration file to see what information is required. Usually the configuration file is located in the root of your project.
*And as always don't forget to read the source code's readme/documentation if there is one*

**Comment by bimaindrawans** [comment]
thankyou, i forget to removed # from hex code
